### ISSUE TITLE
Search page look and feel

### ISSUE THREAD

**Issue by puzzlecanes** [puzzlecanes/client#13]
Make the four icons match the main pink color when they are selected.  You can use  a lighter version of the same color for when they aren't selected.  Maybe just turn the opacity down when not selected. Also make the colors in the drop downs the matching pink to mark the categories and tags that are selected.  Make the search and submit button pink as well.  Basically everything that shows green now should be pink.  The red line row that appears telling you to delete a selection can we changes this to make the font red and the row color still white?This page is a bit hard to use the drop downs.  In the future we may revisit it but good for now.  I think we should put an pink X in top right corner for them to exit out of page if they don't select an image.

**Comment by gmchaturvedi1** [comment]
others things done except the multiselect which i need to understand over call . so we will open other ticket for that so i am closing this for now
