### ISSUE TITLE
calendar control

### ISSUE THREAD

**Issue by puzzlecanes** [puzzlecanes/client#14]
The dates show as 2020-5-4 to 2020-5-10.  Please make it 5/4/2020 to 5/10/2020(Done).  
Make Mon = Monday and be the same color the numbers appear to be(Done).

!Important! -Prev button jumps back a month when it should be a week.  Next button does nothing.

When you click the month button it shows images.  I don't want that for now. For now i just want to use it to navigate quickly to a different week.  I also don't want to see the icons for adding images, text, date and time.

In the future we may do something like this but it will use different data. It will be a separate plan.  I don't want to try to fit all the images from a day for each day of the month into that screen.  That is too much.

We need a way to quickly select another month.

**Comment by gmchaturvedi1** [comment]
![image](https://user-images.githubusercontent.com/10846505/82154727-5dd0d800-988d-11ea-97a0-6e007afb804c.png)
Day and Date is in same line

**Comment by puzzlecanes** [comment]
Nice.  I even like the way the current day is pink.  Although i don't think we will  keep it in the final design because they will likely be using images.

**Comment by gmchaturvedi1** [comment]
![image](https://user-images.githubusercontent.com/10846505/82164132-b5daff00-98cc-11ea-99d0-7c7cdf953240.png)
done

**Comment by gmchaturvedi1** [comment]
Questions on Call - 

1.  Select Month by navigating years one button

**Comment by gmchaturvedi1** [comment]
done
