### ISSUE TITLE
Admin Image edit

### ISSUE THREAD

**Issue by puzzlecanes** [puzzlecanes/client#15]
When editing an image, it doesn't display the image you are editing.  It also says upload and it shouldn't.  It seems to allow you to delete or add tags but it doesn't appear to do anything when you hit the submit button.  It should go back to the view images admin page when you click submit.  Also i have been unable to change the category at all. 

Also on the admin images page the word images at the top left corner seems to be some unusual font.  Please make it match the rest of the site.

**Comment by gmchaturvedi1** [comment]
implemented

**Comment by gmchaturvedi1** [comment]
closed
