### ISSUE TITLE
Text edit window

### ISSUE THREAD

**Issue by puzzlecanes** [puzzlecanes/client#16]
Please change Add Text to be the same font as the rest of the site and the pink.  Please make the text window show the changes they have selected.  The font, size, text color, and back ground color all need to display on the text that they have typed.  This is so they can see it all together before they leave the page.

Please the check box at the bottom to a pink button that says add or update if they are editing the text.

Also when you edit text it adds a new text instead of editing the current one.  

I also dragged the text to a different day then clicked edit and it added a new text box but to the original day.  I don't think the drag and drop is updating the database after each drop.  It should now know it is on a different day and on an image if that happened.  I went off the page to the admin and then clicked back to the planner page.  This forced it to reload and now i had one text box with the update i made but it was on the original day. 

Added 5/16/2020
The radio button that shows with the text should be optional. It defaults to not there and they have a check box to add.

Also Pick a default font and font size.  If user just enters text and wants to save then it will let them because the other font is already defaulted.

**Comment by gmchaturvedi1** [comment]
1. Add and Edit Text With Original font Fixed
2.Color, Background, FontfAmily Preview is now available .(FontSize have some issue i am fixing)

**Comment by gmchaturvedi1** [comment]
closed
