### ISSUE TITLE
Add google fonts.

### ISSUE THREAD

**Issue by puzzlecanes** [puzzlecanes/client#19]
I would like to have the font drop down show the name of each font in that font so they get a preview of what it looks like.  I know loading all of these fonts will slow the web site down.  I believe there is a way to have it load the font but just the letters they are using.  We can do this for just the letters we need in our drop down.  When they pick a font the text they have entered in the Add text page will show the selected font.  Only at that time will we load all the letters, numbers and special characters since we don't know what they will type. Once they have added the text we will know exactly what letters, numbers, special characters we  need.  The planner week will possibly have many different fonts used so we need to take advantage and only load the letters that they are using.  Also it will need to be smart enough to know if the same font is used more then once in the content that is being displayed and add those letters together and just load the font once.

My favorite fonts please just start with these two: 
Dancing Script Impallari Type (4 styles)
Great Vibes TypeSetIt (1 style)

I like the following fonts:
Sriracha
Pacifico
Amatic SC
Satisfy sideshow (1 style)
Kalam Indian Typefoundry(3 styles)
Saccramento Astigmatic(1 style)
Amatic SC
Cookie
Parisienne
Pinyon Script
Alex Brush
Rochester
Lateef
Petiti Formal Script
Rouge Script

**Comment by gmchaturvedi1** [comment]
![image](https://user-images.githubusercontent.com/10846505/82732963-429f1600-9d2e-11ea-907e-9c6057e7bedb.png)

![image](https://user-images.githubusercontent.com/10846505/82732970-4a5eba80-9d2e-11ea-8b95-a6025980b239.png)

i have also fixed the color opening window now it will not  down the background color.the window will will open over background color so no user interface shaking will come :

![image](https://user-images.githubusercontent.com/10846505/82733001-711cf100-9d2e-11ea-8168-fde5fb981bd9.png)

i have not found below fonts in google fonts  : 
1.Petiti Formal Script
2.Saccramento Astigmatic
3.

**Comment by gmchaturvedi1** [comment]
done
