### ISSUE TITLE
Remove dates and days drop down.

### ISSUE THREAD

**Issue by puzzlecanes** [puzzlecanes/client#3]
On main planner page change the From label to Date for now.  I am not really sure what a good title for this would be.  Remove To date since this really isn't needed.   The next drop down is the number of days to display. This day drop down field needs a label of Days for now.  The drop down needs to be made smaller.  The page logic needs to combine the From date with the drop down day amount and display a week or 5 days for that date.  I want it to show the week with the from date in it but I want it to stay always in Monday thru Sunday layout for now.  So that makes it a little tricky maybe.  If you don't want to do the 5 day display option for now that is fine but i would like to be able to pick a date from the from date picker and see that week in the calendar display.

**Comment by gmchaturvedi1** [comment]
removed as discussed
