### ISSUE TITLE
Text display changes

### ISSUE THREAD

**Issue by puzzlecanes** [puzzlecanes/client#5]
For the text display make the radio button optional.  The background color under the text is a bit large it is nice to keep this option but i would like it to just appear behind the text for now.  Maybe it is bigger now because the edit and delete icons are inside it.

**Comment by gmchaturvedi1** [comment]
![image](https://user-images.githubusercontent.com/10846505/75240629-a7f47100-57ea-11ea-8d60-1d0040b56b4c.png)
