### ISSUE TITLE
Edit and delete icon color

### ISSUE THREAD

**Issue by puzzlecanes** [puzzlecanes/client#6]
Edit and delete icon color needs to be changed to match the color of the icons at the top of each day.  Light gray.  It is probably hard to do so it''s ok if you want to leave it until the future but the edit and delete icons should only appear when you hover over an editable element.  Maybe they can just be floating.  For mobile phones they would have to tap the element and then the icons would show up.

**Comment by gmchaturvedi1** [comment]
colors ?

**Comment by gmchaturvedi1** [comment]
Closed
