### ISSUE TITLE
Combine pink header with blue Years Year Month Week header

### ISSUE THREAD

**Issue by puzzlecanes** [puzzlecanes/client#7]
Remove the Pink title (Planner Navigation) but keep the planner drop down.  Maybe can put the planner drop down on the same blue line as the Years\Year\Month\Week views.  Also can we change it to Display only the Month and Year and not "Week 8 (February 2020).  Would like it to just be February 2020.  Also does this really need its own row.  It would be best if it could be moved up to the left of Years\Year\Month\Week views on same row.  Also can we switch the calendar from a blue theme to a light pink theme like the planner navigation had.

**Comment by gmchaturvedi1** [comment]
1.Color is changed 

![image](https://user-images.githubusercontent.com/10846505/75240149-e3db0680-57e9-11ea-800b-87306eaf9b93.png)

2.We can have Month view than . only month will come like the following :

![image](https://user-images.githubusercontent.com/10846505/75240203-fbb28a80-57e9-11ea-877a-37d911eb0a38.png)
